permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Shared Workflow

on:
  workflow_call:
    inputs:
      publish_release:
        description: 'Whether to publish the released .MSI'
        required: false
        type: boolean
        default: false
      push_manifest:
        description: 'Whether to push the WinGet manifest'
        required: false
        type: boolean
        default: false
    secrets:
      PULUMI_BOT_TOKEN:
        required: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Set path for candle and light from WixTools
        run: echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" >> $GITHUB_PATH
        shell: bash

      - name: Generate Pulumi MSI
        run: dotnet run --project ./src -- generate msi
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Sign MSI with Azure Trusted Signing
        uses: azure/artifact-signing-action@v1.2.0
        with:
          endpoint: ${{ steps.esc-secrets.outputs.AZURE_SIGNING_ACCOUNT_ENDPOINT }}
          signing-account-name: ${{ steps.esc-secrets.outputs.AZURE_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name: ${{ steps.esc-secrets.outputs.AZURE_SIGNING_CERT_PROFILE_NAME }}
          azure-tenant-id: ${{ steps.esc-secrets.outputs.AZURE_SIGNING_TENANT_ID }}
          azure-client-id: ${{ steps.esc-secrets.outputs.AZURE_SIGNING_CLIENT_ID }}
          azure-client-secret: ${{ steps.esc-secrets.outputs.AZURE_SIGNING_CLIENT_SECRET }}
          files-folder: ./src
          files-folder-filter: msi
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Publish signed MSI to GitHub release
        if: inputs.publish_release == true
        run: dotnet run --project ./src -- publish msi
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Push WinGet Manifest
        if: inputs.push_manifest == true
        shell: powershell
        run: |
          $download_exists = Test-Path -Path ./src/download-url.txt -PathType Leaf
          if (!$download_exists) {
            echo "./src/download-url.txt file was not found, this means we skipped generating an installer"
            return
          }

          $github_token = "${{ secrets.PULUMI_BOT_TOKEN }}"
          $downloadUrl = Get-Content -Path ./src/download-url.txt
          $version = Get-Content -Path ./src/version.txt
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update Pulumi.Pulumi --urls $downloadUrl --version $version --token $github_token --submit
